import bg1 from '../../assets/images/blog/1.jpg'
import bg2 from '../../assets/images/blog/2.jpg'
import bg3 from '../../assets/images/blog/3.jpg'
import bg4 from '../../assets/images/blog/4.jpg'
import bg5 from '../../assets/images/blog/5.jpg'
import bg6 from '../../assets/images/blog/6.jpg'
import bg7 from '../../assets/images/blog/7.jpg'
import bg8 from '../../assets/images/blog/8.jpg'
import bg9 from '../../assets/images/blog/9.jpg'
import bg10 from '../../assets/images/blog/10.jpg'
import bg11 from '../../assets/images/blog/11.jpg'
import bg12 from '../../assets/images/blog/12.jpg'


import client01 from '../../assets/images/client/01.jpg'
import client02 from '../../assets/images/client/02.jpg'
import client03 from '../../assets/images/client/03.jpg'
import client04 from '../../assets/images/client/04.jpg'
import client05 from '../../assets/images/client/05.jpg'
import client06 from '../../assets/images/client/06.jpg'
import client07 from '../../assets/images/client/07.jpg'
import client08 from '../../assets/images/client/08.jpg'
import client09 from '../../assets/images/client/09.jpg'
import client10 from '../../assets/images/client/10.jpg'
import client11 from '../../assets/images/client/11.jpg'
import client12 from '../../assets/images/client/12.jpg'
import client13 from '../../assets/images/client/13.jpg'

import c1 from '../../assets/images/collection/01.jpg'
import c2 from '../../assets/images/collection/02.jpg'
import c3 from '../../assets/images/collection/03.jpg'
import c4 from '../../assets/images/collection/04.jpg'
import c5 from '../../assets/images/collection/05.jpg'
import c6 from '../../assets/images/collection/06.jpg'
import c7 from '../../assets/images/collection/07.jpg'
import c8 from '../../assets/images/collection/08.jpg'
import c9 from '../../assets/images/collection/09.jpg'
import c10 from '../../assets/images/collection/10.jpg'
import c11 from '../../assets/images/collection/11.jpg'
import c12 from '../../assets/images/collection/12.jpg'
import c13 from '../../assets/images/collection/13.jpg'
import c14 from '../../assets/images/collection/14.jpg'
import c15 from '../../assets/images/collection/15.jpg'

import item1 from '../../assets/images/items/1.jpg'
import item2 from '../../assets/images/items/2.jpg'
import item3 from '../../assets/images/items/3.jpg'
import item4 from '../../assets/images/items/4.jpg'
import item5 from '../../assets/images/items/5.jpg'
import item6 from '../../assets/images/items/6.jpg'
import item7 from '../../assets/images/items/7.jpg'
import item8 from '../../assets/images/items/8.jpg'
import item9 from '../../assets/images/items/9.jpg'
import item10 from '../../assets/images/items/10.jpg'
import item11 from '../../assets/images/items/11.jpg'
import item12 from '../../assets/images/items/12.jpg'
import item13 from '../../assets/images/items/13.jpg'
import item14 from '../../assets/images/items/14.jpg'
import item16 from '../../assets/images/items/16.jpg'
import item17 from '../../assets/images/items/17.jpg'
import item18 from '../../assets/images/items/18.jpg'
import item19 from '../../assets/images/items/19.jpg'
import item20 from '../../assets/images/items/20.jpg'
import item21 from '../../assets/images/items/21.jpg'
import item22 from '../../assets/images/items/22.jpg'
import item23 from '../../assets/images/items/23.jpg'
import item24 from '../../assets/images/items/24.jpg'
import item25 from '../../assets/images/items/25.jpg'
import item26 from '../../assets/images/items/26.jpg'
import item27 from '../../assets/images/items/27.jpg'
import item28 from '../../assets/images/items/28.jpg'
import item29 from '../../assets/images/items/29.jpg'

import gif1 from '../../assets/images/gif/book1.jpg'
import gif2 from '../../assets/images/gif/book2.jpg'
import gif3 from '../../assets/images/gif/book3.jpg'
import gif4 from '../../assets/images/gif/book4.jpg'

import gif5 from '../../assets/images/gif/usb1.jpg'
import gif6 from '../../assets/images/gif/usb2.jpg'
import gif7 from '../../assets/images/gif/usb3.jpg'
import gif8 from '../../assets/images/gif/usb4.jpg'

import gif9 from '../../assets/images/gif/device1.jpg'
import gif10 from '../../assets/images/gif/device2.jpg'
import gif11 from '../../assets/images/gif/device3.jpg'
import gif12 from '../../assets/images/gif/device4.jpg'

import gif13 from '../../assets/images/gif/solution1.jpg'
import gif14 from '../../assets/images/gif/solution2.jpg'
import gif15 from '../../assets/images/gif/solution3.jpg'
import gif16 from '../../assets/images/gif/solution4.jpg'

import gif17 from '../../assets/images/gif/basic1.jpg'
import gif18 from '../../assets/images/gif/basic2.jpg'
import gif19 from '../../assets/images/gif/basic3.jpg'
import gif20 from '../../assets/images/gif/basic4.jpg'
// Tuyển dụng
import t1 from '../../assets/images/recruitment/1.jpg'
import t2 from '../../assets/images/recruitment/2.jpg'
import t3 from '../../assets/images/recruitment/3.jpg'

import work1 from '../../assets/images/work/1.jpg'
import work2 from '../../assets/images/work/2.jpg'
import work3 from '../../assets/images/work/3.jpg'
import work4 from '../../assets/images/work/4.jpg'
import work5 from '../../assets/images/work/5.jpg'
import work6 from '../../assets/images/work/6.jpg'
import work7 from '../../assets/images/work/7.jpg'
import work8 from '../../assets/images/work/8.jpg'
import work9 from '../../assets/images/work/9.jpg'
import work10 from '../../assets/images/work/10.jpg'
import work11 from '../../assets/images/work/11.jpg'
import work12 from '../../assets/images/work/12.jpg'

import bg01 from '../../assets/images/bg/01.jpg'
import bg02 from '../../assets/images/bg/02.jpg'
import bg03 from '../../assets/images/bg/03.jpg'
import bg04 from '../../assets/images/bg/04.jpg'
import bgImage from '../../assets/images/bg/bg02.png'
import cta from '../../assets/images/cta.png'
import creator from '../../assets/images/client/creator.png'
import logo48 from '../../assets/images/icon-logo-48.png'
import single from '../../assets/images/blog/single.jpg'
import lightLogo from '../../assets/images/logo-light.png'
import office from '../../assets/images/svg/office-desk.svg'
import ofcDesk from '../../assets/images/svg/office-desk.svg'
import prodToCard from '../../assets/images/svg/products-to-cart-or-basket.svg'

import MetaMask_Fox from '../../assets/images/wallet/MetaMask_Fox.svg'
import aave from '../../assets/images/wallet/aave.svg'
import Airswap from '../../assets/images/wallet/Airswap.svg'
import Compound from '../../assets/images/wallet/Compound.svg'
import DDEX from '../../assets/images/wallet/ddexsvg.svg'
import defiSaver from '../../assets/images/wallet/defi-saver.svg'
import dYdX from '../../assets/images/wallet/dYdX.svg'
import IDEX from '../../assets/images/wallet/idex.svg'
import Kyber from '../../assets/images/wallet/kyber.svg'
import Maker from '../../assets/images/wallet/maker.svg'
import NUO from '../../assets/images/wallet/nuo.svg'
import PoolTogether from '../../assets/images/wallet/PoolTogether.svg'
import Sablier from '../../assets/images/wallet/sablier.svg'
import set from '../../assets/images/wallet/set.svg'
import Uniswap from '../../assets/images/wallet/uniswap.svg'
import Zerion from '../../assets/images/wallet/zerion.svg'
import logoDark from '../../assets/images/logo-dark.png'
import whiteLogo from '../../assets/images/logo-white.png'
import itemDetail from '../../assets/images/items/item-detail.jpg'
import itemDetail1 from '../../assets/images/items/item-detail-1.jpg'
import ErrorImage from '../../assets/images/error.png'
import united from '../../assets/images/svg/united.png'
import community from '../../assets/images/svg/community.png'
import playStore from '../../assets/images/playstore.png'
import app from '../../assets/images/app.png'
import iconLogo from '../../assets/images/icon-logo-64.png'
import character from '../../assets/images/character.png'
// giới thiệu
import about from '../../assets/images/about.jpg'
import certificate1 from '../../assets/images/about/certificate1.jpg'
import certificate2 from '../../assets/images/about/certificate2.jpg'
import certificate3 from '../../assets/images/about/certificate3.jpg'
import certificate4 from '../../assets/images/about/certificate4.jpg'
import certificate5 from '../../assets/images/about/certificate5.jpg'
import certificate6 from '../../assets/images/about/certificate6.jpg'
import certificate7 from '../../assets/images/about/certificate7.jpg'
import certificate8 from '../../assets/images/about/certificate8.jpg'
import certificate9 from '../../assets/images/about/certificate9.jpg'
import certificate10 from '../../assets/images/about/certificate10.jpg'
import certificate11 from '../../assets/images/about/certificate11.jpg'


import sp1 from '../../assets/images/product/product1.jpg'
import sp2 from '../../assets/images/product/product2.jpg'
import sp3 from '../../assets/images/product/product3.jpg'
import sp4 from '../../assets/images/product/product4.jpg'

export {
  bg1, bg2, bg3, bg4, bg5, bg6, bg7, bg8, bg9, bg10, bg11, bg12,
  client01, client02, client03, client04, client05, client06, client07, client08,
  client09, client10, client11, client12, client13,
  c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15,
  item1, item2, item3, item4, item5, item6, item7, item8, item9, item10, item11, item12, item13, item14,
  item16, item17, item18, item19, item20, item21, item22, item23, item24, item25, item26, item27, item28, item29,
  gif1, gif2, gif3, gif4, gif5, gif6, gif7, gif8, gif9, gif10, gif11, gif12, gif13, gif14, gif15, gif16, gif17, gif18, gif19, gif20,
  work1, work2, work3, work4, work5, work6, work7, work8, work9, work10, work11, work12,
  bg01, bg02, bg03, bg04, bgImage,
  about, cta, creator, logo48, single, lightLogo, office, ofcDesk, prodToCard,
  MetaMask_Fox, aave, Airswap, Compound, DDEX, defiSaver, dYdX, IDEX, Kyber, Maker, NUO, PoolTogether, Sablier, set, Uniswap, Zerion, logoDark, whiteLogo,
  itemDetail, itemDetail1, ErrorImage, united, community, sp1, sp2, sp3, sp4,t1,t2,t3,
  playStore, app, iconLogo, character, certificate1, certificate2, certificate3, certificate4, certificate5, certificate6, certificate7, certificate8, certificate9, certificate10, certificate11
}